# Generated by Django 6.0.2 on 2026-02-19 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_createservice_service_discount_service_status_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table=None,
        ),
    ]
