# Generated by Django 6.0.2 on 2026-02-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateService',
        ),
        migrations.RemoveField(
            model_name='service',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.DeleteModel(
            name='ServiceList',
        ),
    ]
