# Generated by Django 6.0.2 on 2026-02-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_delete_createservice_remove_service_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='serviceDescription',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='serviceName',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='servicePrice',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='serviceStatus',
            field=models.BooleanField(default=True),
        ),
    ]
