# Generated by Django 6.0.2 on 2026-02-20 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_description_service_servicedescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='serviceDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='serviceName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='servicePrice',
            new_name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.category'),
        ),
    ]
