# Generated by Django 6.0.2 on 2026-02-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
