# Generated by Django 6.0.2 on 2026-02-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('employeeAge', models.IntegerField()),
                ('employeeCity', models.CharField(max_length=40)),
                ('employeeEmail', models.EmailField(max_length=254, null=True)),
                ('employeeSalary', models.IntegerField()),
                ('employeeStatus', models.BooleanField(default=True)),
                ('post', models.CharField(max_length=100)),
                ('join_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
