# Generated by Django 6.0.2 on 2026-02-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employeeAge',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeCity',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeSalary',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employeeStatus',
            new_name='status',
        ),
    ]
