# Generated by Django 6.0.2 on 2026-02-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_employeeage_employee_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
