# Generated by Django 6.0.2 on 2026-02-04 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
