# Generated by Django 6.0.2 on 2026-02-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_studentemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('productStock', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
