# Generated by Django 6.0.2 on 2026-02-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productColor',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='productStatus',
            field=models.BooleanField(default=True),
        ),
    ]
