# Generated by Django 6.0.2 on 2026-02-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_product_productcolor_product_productstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('studentName', models.CharField(max_length=100)),
                ('studentMarks', models.IntegerField()),
                ('studentGrade', models.CharField(max_length=10)),
                ('studentStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'studentresult',
            },
        ),
    ]
