# Generated by Django 6.0.2 on 2026-02-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('studentName', models.CharField(max_length=100)),
                ('studentCourse', models.CharField(max_length=100)),
                ('studentStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'studentcourse',
            },
        ),
    ]
