# Generated by Django 6.0.2 on 2026-02-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentHobbies', models.CharField(choices=[('reading', 'reading'), ('Writing', 'Writing'), ('Travel', 'Travel'), ('Music', 'Music')], max_length=100)),
                ('studentAddress', models.CharField(max_length=100)),
                ('studentPhone', models.CharField(max_length=10)),
                ('studentGender', models.CharField(max_length=10)),
                ('studentDOB', models.DateField()),
                ('studentid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'StudentProfile',
            },
        ),
    ]
