# Generated by Django 6.0.2 on 2026-02-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_category_alter_studentprofile_table_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.IntegerField(null=True),
        ),
    ]
