# Generated by Django 6.0.2 on 2026-02-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_service_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='categoryId',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='studentid',
            new_name='studentId',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='studentName',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='studentName',
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
