# Generated by Django 6.0.2 on 2026-02-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
