# Generated by Django 6.0.2 on 2026-02-20 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_service_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
